sudo: required
services:
  - docker

before_install:
  - docker build -t nfuser/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nfuser/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-app"
  env: "Docker-app-env"
  bucket_name: "elasticbeanstalk-eu-north-1-246249304338"
  bucker_path: "docker-app"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"